# Generated by Django 4.2.5 on 2023-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
