# Generated by Django 4.2.5 on 2023-10-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_alter_commit_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
